### ISSUE TITLE
C++ standard support?

### ISSUE THREAD

**Issue by asmaloney** [mariusbancila/stduuid#11]
Does this require C++17?

I don't see any mention of C++ versions in the README, but the header includes `<optional>` which - as far as I can tell - is a C++17 header.

(I wanted to use this with C++11...)

**Comment by mariusbancila** [comment]
Yes, it is intended for C++17. You can replace std::optional with boost::optional if you want. Or you can fork it and change the parts that don't suit your needs. The idea this is supposed to be the implementation of the proposal for standardization (C++20 or beyond).

**Comment by asmaloney** [comment]
Ah - that's unfortunate. I don't want to include Boost.

I was hoping this was like the [std::variant](https://github.com/mpark/variant) implementation I'm using that makes a new standard (or potential in this case) available to earlier C++ versions.

Thanks!
