### ISSUE TITLE
Build broken for 4 months

### ISSUE THREAD

**Issue by jwmelto** [mariusbancila/stduuid#14]
The Travis build has been broken for 3 months. The last commit was 3 months ago. Is this project being maintained?

**Comment by mariusbancila** [comment]
The build fails because a test is not passing. The time generator has a pretty simple implementation and produces 1-2 collisions for a loop of 1000 uuids.

**Comment by mariusbancila** [comment]
Also, the time generator uses a function to retrieve the MAC address that is only implemented for Windows. Therefore, when building Travis with gcc on Linux the results were not what was expected, so the test failed.

**Comment by mariusbancila** [comment]
I removed the test to the time generator on other platforms than Windows.

Keep in mind that the implementation of this generator is currently very simplistic and not intended for any sort of production code.
