### ISSUE TITLE
from_string should be taking string_view

### ISSUE THREAD

**Issue by Lastique** [mariusbancila/stduuid#20]
The discussion in P0959R3 section VIII, "Why `string` and `char*` instead of `string_view`?", is based on the incorrect premise that `std::basic_string` has no implicit conversion to `std::basic_string_view`. This is not true, as `std::basic_string` [does have](http://eel.is/c++draft/basic.string) an implicit conversion operator to `std::basic_string_view`. The provided examples in that discussion would compile.

I think, there is no reason to not have a single `from_string` accepting `std::basic_string_view`.

**Comment by mariusbancila** [comment]
The problem here is that template argument deduction does not work. Let me explain:

This example works:
```
#include <iostream>
#include <string>
#include <string_view>

void foo(std::string_view s)
{
    std::cout << s.data() << '\n';
}

int main()
{
    foo("hello, world!");
    
    std::string s = "hello, mello!";
    foo(s);
}
```

But this one fails:
```
#include <iostream>
#include <string>
#include <string_view>

template<class CharT = char, 
         class Traits = std::char_traits<CharT>>
void foo(std::basic_string_view<CharT, Traits> s)
{
    std::cout << s.data() << '\n';
}

int main()
{
    foo("hello, world!");
    
    std::string s = "hello, mello!";
    foo(s);
}
```
with the following errors:
```
prog.cc: In function 'int main()':
prog.cc:14:24: error: no matching function for call to 'foo(const char [14])'
   14 |     foo("hello, world!");
      |                        ^
prog.cc:7:6: note: candidate: 'template<class CharT, class Traits> void foo(std::basic_string_view<_CharT, _Traits>)'
    7 | void foo(std::basic_string_view<CharT, Traits> s)
      |      ^~~
prog.cc:7:6: note:   template argument deduction/substitution failed:
prog.cc:14:24: note:   mismatched types 'std::basic_string_view<_CharT, _Traits>' and 'const char*'
   14 |     foo("hello, world!");
      |                        ^
prog.cc:17:10: error: no matching function for call to 'foo(std::string&)'
   17 |     foo(s);
      |          ^
prog.cc:7:6: note: candidate: 'template<class CharT, class Traits> void foo(std::basic_string_view<_CharT, _Traits>)'
    7 | void foo(std::basic_string_view<CharT, Traits> s)
      |      ^~~
prog.cc:7:6: note:   template argument deduction/substitution failed:
prog.cc:17:10: note:   'std::__cxx11::basic_string<char>' is not derived from 'std::basic_string_view<_CharT, _Traits>'
   17 |     foo(s);
      |          ^
```

Can be fixed with this:
```
foo<char, std::char_traits<char>>("hello, world!");
    
std::string s = "hello, mello!";
foo<char, std::char_traits<char>>(s);
```
But that's not something you want to write.

That's why those two overloads are needed.

**Comment by Lastique** [comment]
In that case you need a third overload that takes `std::string_view` because neither of the two overloads (`std::string` or `const char*`) would accept `std::string_view` implicitly.

I think, having overloads taking all kinds of `std::basic_string_view` (i.e. `std::string_view`, `std::wstring_view`, `std::u16string_view`, `std::u32string_view`) is preferable. This way you would avoid the dependency on `std::string` and still support all use cases.

**Comment by Lastique** [comment]
Note that `std::string_view` allows not only to avoid dynamic memory allocation, but it also allows to use non-zero terminated strings without copying. Parsing a portion of a larger string is not an uncommon use case, so I think `std::string_view` needs to have first class support.

**Comment by tusharpm** [comment]
@mariusbancila I enabled `std::basic_string_view` arguments for `uuid::is_valid_uuid`, `uuid::from_string` and `uuid_name_generator::operator()` in [my fork](https://github.com/tusharpm/stduuid/tree/modern_cpp) maintaining compatibility for `const char *` and `std::basic_string`. I haven't tested with custom `Traits` yet, but that should be fixable with more type_traits machinery.

For instance, we can modify your example code as: [Godbolt link](https://godbolt.org/z/5WzG8G8xj)
```cpp
#include <iostream>
#include <string>
#include <string_view>
#include <type_traits> // need `std::decay_t`

template <typename StringType>
constexpr inline auto to_string_view(StringType const & str) ->
   std::basic_string_view<std::decay_t<decltype(str[0])>>
{
   return str;
}

template <typename StringType>
void foo(StringType const & s)
{
    std::cout << to_string_view(s) << '\n';
}

int main()
{
    foo("hello, world!");
    
    std::string s = "hello, mello!";
    foo(s);

    std::string_view v = "hello, yellow!";
    foo(v);
}
```
Please let me know if this works for you and if you'd be interested in reviewing this in a PR.

PS: my branch also has miscellaneous updates/optimization. I can send a PR for those if they look interesting.

**Comment by tusharpm** [comment]
Follow up on custom Traits: [This version](https://godbolt.org/z/E31bf4q9z) preserves the input parameter's traits.
```cpp
#include <iostream>
#include <string>
#include <string_view>

template <typename StringType>
constexpr inline std::basic_string_view<
    typename StringType::value_type,
    typename StringType::traits_type>
to_string_view(StringType const & str)
{
    return str;
}

template <typename CharT>
constexpr inline std::basic_string_view<CharT>
to_string_view(CharT const * str)
{
    return str;
}

template <typename StringType>
void foo(StringType const & s)
{
    std::cout << to_string_view(s) << '\n';
}

int main()
{
    foo("hello, string literal!");
    
    std::string s = "hello, string!";
    foo(s);

    std::string_view view = "hello, string_view!";
    foo(view);
}
```
Furthermore, this doesn't use `std::decay_t` either.
