### ISSUE TITLE
Consider making global constants inline

### ISSUE THREAD

**Issue by Lastique** [mariusbancila/stduuid#21]
I think, `uuid` constants `uuid_namespace_dns`, `uuid_namespace_url`, `uuid_namespace_oid` and `uuid_namespace_x500` should be marked `inline` in the P0959R3 proposal so that they are not duplicated in multiple translation units. Such is the current practice wrt. other global constants, like those for [memory order](http://eel.is/c++draft/atomics.order) in atomics.

**Comment by mariusbancila** [comment]
That is a good suggestion. I have incorporated it into the proposal.
