### ISSUE TITLE
Error: 'value' is unavailable: introduced in macOS 10.14

### ISSUE THREAD

**Issue by Czarek-Mojang** [mariusbancila/stduuid#22]
I am using latest available clang `11.0.3 `and from what I read it supports C++17. Running on Catalina `15.5` with all latest updates to comand line tools and I am getting this error:

```
/third_party/stduuid/include/stduuid/uuid.h:900:47: error: 'value' is unavailable: introduced in
      macOS 10.14
            memcpy(&data[10], &device_address.value()[0], 6);
                                              ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/optional:952:27: note: 'value' has been explicitly marked
      unavailable here
    constexpr value_type& value() &
```

I am building with base SDK `10.15` on latest Catalina with newest clang, however I have set Target SDK to `10.10`, because my application needs to run on older OSes. I guess that target SDK is causing the error.

What are my options here? Should I fix that single error or will there be more with my configuration?

**Comment by mariusbancila** [comment]
The `uuid_time_generator` is just an experimental implementation. Should not be used.

`std::optional` is required for this code to compile.
