### ISSUE TITLE
patch release?

### ISSUE THREAD

**Issue by nholthaus** [mariusbancila/stduuid#24]
I was wondering if you'd consider creating a patch release tag for what's currently in master. The changes to the CMakeLists.txt to avoid building the unit tests would be very helpful to have versioned.

Thanks for building such an awesome library!

**Comment by NorbertNemec** [comment]
Second that. There are plenty of valuable changes since 1.0 and for many purposes it is suboptimal to pick just some an arbitrary commit for a project dependency.

**Comment by sketchylizard** [comment]
I would also like to ask for a patch release. I'm trying to use CPM for CMake for managing our dependencies. It wants a version number to checkout though and v1.0 doesn't build for me--the -stdc++latest flag to the compiler conflicts with my own c++17 flag and I've had problems building the tests on Android so I want to disable them.

**Comment by mariusbancila** [comment]
I made the release v1.1: https://github.com/mariusbancila/stduuid/releases/tag/v1.1
