### ISSUE TITLE
Where to get dependency gsl?

### ISSUE THREAD

**Issue by pcsagan** [mariusbancila/stduuid#36]
I have a C++17 project that I tried adding this library to, but I'm getting the error:

The contents of <span> are available only with C++20 or later.
stduuid\include\uuid.h(58,17): error C2653: 'gsl': is not a class or namespace name

I'm using MSVC.

**Comment by mariusbancila** [comment]
GSL is the Guideline Support Library that implements recommendations from the C++ Core Guidelines. It is available here: https://github.com/microsoft/GSL
