### ISSUE TITLE
"Comparison of unsigned expression < 0 is always false" in operator+

### ISSUE THREAD

**Issue by dfct** [mariusbancila/stduuid#4]
Hi Marius,

While trialing this library in a project of mine, clang on macOS is warning about two comparisons of unsigned expression < 0 in operator+. Specifically, this if statement in both uuid_const_iterator and uuid_iterator:

```
(...)

self_type & operator+=(difference_type const offset)
         {
            if (index + offset < 0 || index + offset > uuid::state_size)
                     (...)
```  

Seems `difference_type` `offset` is a `ptrdiff_t` / signed, but `index` is a `size_t` / unsigned .

**Comment by mariusbancila** [comment]
It's fixed. Thank you.

**Comment by dfct** [comment]
Cheers! :)
