### ISSUE TITLE
Description is stating c++17 support but...

### ISSUE THREAD

**Issue by mrspirytus** [mariusbancila/stduuid#44]
Hello,

Trying to build this code on Linux using g++ (-std=c++17) with c++17 I get error not able to find 
```
#include <span>
```
 which is the c++20 feature. [span](https://en.cppreference.com/w/cpp/header/span)

```
$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
```

**Comment by mariusbancila** [comment]
When you build the project with cmake, there is a variable called `UUID_USING_CXX20_SPAN`. It's `OFF` by default, which means the GLS span should be used. There is a gls folder within the project and contains a span implementation.

**Comment by mariusbancila** [comment]
Better documentation is now provided in the readme.md file.
