### ISSUE TITLE
Check for CoCreateGuid failure

### ISSUE THREAD

**Issue by stephenatwork** [mariusbancila/stduuid#46]
A static analysis tool has highlighted that the return HRESULT of CoCreateGuid is not checked.
It seems unlikley, but I guess we should check & throw?

**Comment by stephenatwork** [comment]
Here's a suggested patch

[system_error_patch.txt](https://github.com/mariusbancila/stduuid/files/7266471/system_error_patch.txt)

**Comment by mariusbancila** [comment]
Thanks for the suggestion. I've fixed it.
