### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by yca** [mariusbancila/stduuid#49]
I'm trying to use this library for a cross-platform project but I'm taking GSL span errors. As far as I understand it is currently only possible to build the project using GSL?

**Comment by yca** [comment]
I first tried on Windows, compiler is MSVC 16.11.31613 (MSVC 2019). It fell backed to GSL path and throw "undefined symbol gsl ..." kind of an error.

The thing is I thought since the library is a single header, I only copied the header to my project and not the GSL folder.

**Comment by mariusbancila** [comment]
`std::span` is only supported in VS 2019 16.6. So then you need to use GSL and you need this library, otherwise, it cannot work.
