### ISSUE TITLE
Duplicate to_string and to_wstring symbols when compiling

### ISSUE THREAD

**Issue by dfct** [mariusbancila/stduuid#5]
It appears the to_string(uuid const & id) and to_wstring(uuid const & id) free functions in uuid.h are non-static and non-inline, triggering a duplicate symbols error when compiling code that includes uuid.h within different translation units. 

Can they be made static or inline?

**Comment by mariusbancila** [comment]
That was a good observation. Someone I just missed that simple thing. 

I fixed that by making the two non-member functions, `to_string()` and `to_wstring()`, inline.

**Comment by dfct** [comment]
Grand, thank you! Can confirm things are working for me now.
