### ISSUE TITLE
Please create new release for gcc compilation error

### ISSUE THREAD

**Issue by toge** [mariusbancila/stduuid#59]
Hello.
I'm trying to update conan's recipe. 
Conan's recipe support only v1.0 (https://conan.io/center/stduuid)

I met compilation error on gcc.
Master of stduuid is already fixed this problem.
https://github.com/mariusbancila/stduuid/commit/c4728ee83b8d37f0579c13c6b49f6f108cdf1978

Would you have new release including this fix?

**Comment by mariusbancila** [comment]
Done.
https://github.com/mariusbancila/stduuid/releases/tag/v1.2.2

**Comment by toge** [comment]
Thank you for quick response!
