### ISSUE TITLE
vcpkg problem

### ISSUE THREAD

**Issue by mehah** [mariusbancila/stduuid#63]
I saw that the project is in vcpkg, but I can't install it.
https://vcpkg.info/port/stduuid

however it is not found in the ports folder in vcpkg:
https://github.com/microsoft/vcpkg/tree/master/ports/stduuid
![image](https://user-images.githubusercontent.com/2267386/161981821-9c6f76f1-d4a8-4b6d-8962-d71cf2cbe563.png)

**Comment by mariusbancila** [comment]
This is not something I did. Nor something I have experience with.

**Comment by marmichalski** [comment]
@mehah it's not, see https://github.com/microsoft/vcpkg/pull/20161

**Comment by mehah** [comment]
> This is not something I did. Nor something I have experience with.
I understand, your library is good, it would be interesting to embed it in vcpkg.

> @mehah it's not, see [microsoft/vcpkg#20161](https://github.com/microsoft/vcpkg/pull/20161)
> 
> Also, official vcpkg packages list is here: https://vcpkg.io/en/packages.html
thx

**Comment by BurningEnlightenment** [comment]
stduuid is now available on vcpkg.

**Comment by mariusbancila** [comment]
Excellent! Great news. Thank you for the work.
