### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by Klaim** [mariusbancila/stduuid#73]
Hi! I'm currently attempting to make a conda-forge package of this library (see https://github.com/conda-forge/staged-recipes/pull/20182). 

However, v1.2.2 cannot be packaged because of the issues that have been fixed regarding gsl handling and C++17 are in master and not in a released version.

Do you have plans to release the current master soon? It would be helpful if you tag the current master at least, it seems stable enough.

Some issues I noted while attempting to package (based on current master):
- the version of the library is not specified in the CMake files
- the include directory is not prefixed with the project name, this can be a source of conflict: doing `#include <uuid.h>` might not include that project's header. Preferably `#include <stduuid/uuid.h>` should work. If you agree, I think changing the major version might help as a heads-up for users. If you want to keep compatibility, it's possible to provide both (although I wouldnt recommend it)
- this project isn't well setup for allowing dependencies from coming from "outside", mostly a package manager or the environment. Namely, gsl is not acquired through `find_package` but it should, except when relying on `std::span`. The addition of the gsl directory automatically in include directories can conflict with a gsl version from package manager or environment. Basically, there are several changes to do to fix that.

As part of packaging this library for conda-forge I can create patches specific to that package, so these are not blockers for me. Having a more recent tag/release is a blocker however.

**Comment by paulocoutinhox** [comment]
+1

**Comment by mariusbancila** [comment]
See https://github.com/mariusbancila/stduuid/releases/tag/v1.2.3

**Comment by Klaim** [comment]
Thanks!
