### ISSUE TITLE
is it support android or ios??

### ISSUE THREAD

**Issue by sczybt** [mariusbancila/stduuid#8]
...

**Comment by mariusbancila** [comment]
iOS should be supported. The same system APIs that create uuids on Mac OS should be also available on iOS, as far as I know. But Android is not supported.

**Comment by dan-ryan** [comment]
"But Android is not supported"
What's so different in the NDK? When will it be supported?

**Comment by mariusbancila** [comment]
If anyone is willing to implement this for Android I'll gladly take PR. But for the time being, I do not have the possibility myself to implement it.
